# Generated by Django 5.2.9 on 2026-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='avatars/default.png', upload_to='image_posts/'),
        ),
    ]
