# Generated by Django 5.2.9 on 2026-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='posts_count',
            field=models.IntegerField(),
        ),
    ]
