# Generated by Django 5.2.9 on 2026-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
