# Generated by Django 5.2.9 on 2026-03-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
