# Generated by Django 5.2.9 on 2026-03-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
